source 'https://github.com/CocoaPods/Specs.git'
#私有仓库
source 'http://172.20.10.91/mobile/pod_specs.git'

platform :ios, '10.0'

target 'LogDemo01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CocoaLumberjack', '3.5.0'
#  pod 'AFNetworking'
#  pod 'OpenCV', '~>2.4'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ARCHS'] = 'armv7 arm64'
      if config.name == 'Debug'
        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      end
    end
  end
end
